### ISSUE TITLE
Spelling mistake for my username in the datapack resources

### ISSUE THREAD

**Issue by y2k04** [eingruenesbeb/Villager-Bonk#2]
Was labeled as Y2K2 instead of Y2K4 lmao

**Comment by y2k04** [comment]
![image](https://github.com/user-attachments/assets/25e21762-f13c-44aa-9860-084074282814)

**Comment by eingruenesbeb** [comment]
Oh, that's emberassing 😅. 
I'll fix that.

**Comment by eingruenesbeb** [comment]
Alright, I edited the description and edited every download to point to the corrected version.
Should be resolved.
